### PR TITLE
Version bumps for 4.30 stream

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1319

**Comment by akurtakov** [comment]
Host bumped via https://github.com/eclipse-platform/eclipse.platform.swt/commit/045615f74a479fd652f4420efcb3d46433ca0d98  thus merging this one.

**Comment by akurtakov** [comment]
Starting new I-build to see what's left.

**Comment by deepika-u** [comment]
Thanks for the update.

**Pull request merged**
