### PR TITLE
Add missing output specifications in build.properties

### PR DESCRIPTION
**Pull request by HeikoKlare**

### CODE REVIEW

**Comment by HannesWell** [comment]
@HeikoKlare is this still relevant?
And although it is actually obvious that this is required, can you tell how you noticed this is missing?

**Comment by HeikoKlare** [comment]
I provided this PR together with PRs to all other Eclipse Platform repositories when we had an issue with the API baseline comparison in Tycho. If I remember correctly, the reason was that the baseline comparison uses the Eclipse compiler to generate the class files to compare, which output into the output folder according to the Eclipse project settings (i.e., as defined in the `.classpath`). The baseline comparison then uses what is specified as the output folder in the `build.properties`, which is why this usually has to be defined as `bin`. I systematically scanned and corrected all the `build.properties` files to have everything consistent, which is how I created this PR, even though there have not been any actual build problems with SWT binaries, as far as I remember.

With respect to the SWT binaries, I am not sure whether it is really relevant, as I think the compilation is done via ANT and no baseline comparison happens during the build. So probably we can simply drop this PR (or merge it for the sake of consistency to all other projects, even though it probably won't have any effect).

**Comment by HannesWell** [comment]
Thanks for the elaboration and fixing all repos.


> With respect to the SWT binaries, I am not sure whether it is really relevant, as I think the compilation is done via ANT and no baseline comparison happens during the build. So probably we can simply drop this PR (or merge it for the sake of consistency to all other projects, even though it probably won't have any effect).

In this case I also tend to say that we should just leave it as it is for now, especially since I (hopefully soon) will replace the ant compilation with a maven compilation of the Java files as part of https://github.com/eclipse-platform/eclipse.platform.swt/issues/513 and also wanted to further unify the build of the fragments.

**Comment by HeikoKlare** [comment]
> In this case I also tend to say that we should just leave it as it is for now

Agreed. Thus closing this PR. Thanks for your work on simplifying the binaries/fragments build! Really looking forward to having the ANT build for the binaries replaced.

**Pull request closed without merging**
