### PR TITLE
Store SWT native binaries using Git-LFS

### LINKED ISSUE #2: Merge swt.binaries repo in the swt one
There was a good question asked on https://github.com/eclipse-platform/eclipse.platform/issues/7 - why don't we use git LFS for SWT binaries? As of today, SWT is about 250 MB and it seems that the github [provides 1 GB free bandwidth for git LFS repos](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage), so it should be enough.

The benefit is surely that we don't need to synchronize two repos and have platform code & binaries in one, plus much faster clone.

### PR DESCRIPTION
**Pull request by HannesWell**
This draft is a first attempt to configure this Git-repository to store the native binaries (*.dll, *.so and *jnilib) using Git Large File Storage (LFS) and convert all existing files correspondingly.

Eventually we probably want to re-write the history to convert all commit binary artifacts to use LFS, at least when this repo is merged into eclipse.platform.swt.

Since the [1GB LFS bandwith provided by GitHub for free](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage#tracking-storage-and-bandwidth-use) will probably not be sufficient and at the moment I see two options to tackle it:
- Buy a extra data pack from GitHub:
https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage#purchasing-additional-storage-and-bandwidth
`"One data pack costs $5 per month, and provides a monthly quota of 50 GB for bandwidth and 50 GB for storage"`, which I assume will be sufficient. If not a second one does not cost too much (IMHO).
- Try to configure this repo to use a storage server hosted at EF-infra.
I believe this tells us how to do it: https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-config.adoc
We could try to set the `lfs.url` to a https URL so that everyone can clone and use a SSH URL for `lfs.pushurl` that can only be used by the Releng Jenkins CI.
 

If this is eventually merged the SWT Oomph setup should be adjusted to install the `org.eclipse.jgit.lfs`.
@iloveeclipse do you know if this still requires a local git(-lfs) installation or is this already fully implemented in jgit? I just found a forum post from 2016, that says it is planned to fully support it.

Fixes https://github.com/eclipse-platform/eclipse.platform.swt.binaries/issues/2

### CODE REVIEW

**Comment by HannesWell** [comment]
Have to adjust the build to clone with LFS enabled.

**Comment by laeubi** [comment]
@HannesWell we could probabbly use the download.eclipse server for pull, and configure push to use the scp connection?

**Comment by HannesWell** [comment]
> @HannesWell we could probabbly use the download.eclipse server for pull, and configure push to use the scp connection?

That's what I had in mind, altough I'm not sure if it is really scp or just a ssh address, maybe with a user.

**Comment by HannesWell** [comment]
Closing this in favor of https://github.com/eclipse-platform/eclipse.platform.swt/pull/956.

**Pull request closed without merging**
