### PR TITLE
build.properties: remove non-existing src folder

### PR DESCRIPTION
**Pull request by jukzi**

### CODE REVIEW

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt.binaries/pull/61 looks like superset of this one

**Comment by akurtakov** [comment]
This patch seems to have totally broken the build - aka src folder is used?

**Comment by jukzi** [comment]
indeed
```
15:30:59  [INFO] Executing tasks
15:30:59  [INFO]      [copy] Copying 693 files to /home/jenkins/agent/workspace/ipse.platform.swt.binaries_PR-65/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.win32.win32.x86_64/src
```

**Comment by HeikoKlare** [comment]
The ANT tasks of the build copy the OS-dependent source files to the according OS fragment's `src` folder:

> 15:30:59  [INFO] Executing tasks
15:30:59  [INFO]      [copy] Copying 693 files to /home/jenkins/agent/workspace/ipse.platform.swt.binaries_PR-65/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.win32.win32.x86_64/src

When removing the folder from the `build.properties`, probably the resulting bundle will be empty and thus the classes cannot be found.

**Comment by laeubi** [comment]
Please dont mess with the buildfiles for SWT as these are build in a special way with **ant** not **maven**...

**Pull request closed without merging**
